### ISSUE TITLE
utf-8 unicode

### ISSUE THREAD

**Issue by victorjambo** [molnarjani/zuora-aqua-client-cli#11]
use `r.content.decode("utf-8")` to support utf-8 unicode. 
Example:
`r.text` returns `ä»æ°,å·å³¶`
`r.content.decode("utf-8")` returns `仁氏,川島`
r.text returns unknown symbols instead of chinese characters

https://github.com/molnarjani/zuora-aqua-client-cli/blob/06ead723db99a214b0e45c0ce2e1e20887f41fb7/zuora_aqua_client_cli/run_zoql.py#L110

**Comment by molnarjani** [comment]
Thanks @victorjambo
The fix is now available in  v0.1.11
